const fs=require('node:fs');
process.chdir(__dirname);
const controls="<header class=\"room-title\"><div><span>THE STOLEN RAINBOW</span><strong>전투 플레이룸</strong></div><a href=\"index.html\">본편 열기 ↗</a></header>\n<section id=\"reviewbar\" aria-label=\"플레이룸 조작\">\n<nav role=\"tablist\" aria-label=\"도구 선택\"><button role=\"tab\" aria-selected=\"true\" data-panel=\"combat-pane\">전투</button><button role=\"tab\" aria-selected=\"false\" data-panel=\"lab-pane\">공격 연습</button><button role=\"tab\" aria-selected=\"false\" data-panel=\"review-pane\">검토 도구</button></nav>\n<div class=\"context\"><label>요일 <select id=\"scene\"></select></label><label class=\"check\"><input id=\"safe\" type=\"checkbox\"> 무적 연습</label><button id=\"toggle-play\">재생 / 정지</button><output id=\"scene-status\"></output></div>\n<div class=\"pane\" id=\"combat-pane\" role=\"tabpanel\"><div class=\"row\"><button id=\"play-scene\" class=\"primary\">전투 시작</button><button id=\"title-view\">타이틀 / 처음부터</button><span id=\"day-help\"></span></div></div>\n<div class=\"pane\" id=\"lab-pane\" role=\"tabpanel\" hidden><div class=\"row\"><label>공격 <select id=\"weapon\"></select></label><button id=\"weapon-play\" class=\"primary\">직접 연습</button><button id=\"weapon-demo\">한 발 궤적</button></div><p id=\"weapon-help\"></p><details><summary>실전 상황 연습</summary><div class=\"row\"><label>상황 <select id=\"tactic\"><option value=\"0\">빨강 · 다섯 탄열</option><option value=\"1\">주황 · 독립된 세 무리</option><option value=\"2\">노랑 · 세 겹 뒤 발사원</option><option value=\"3\">초록 · 옆에서 발사원 추적</option><option value=\"4\">파랑 · 끊어진 전면 파도</option><option value=\"5\">남색 · 사방에서 접근</option><option value=\"6\">보라 · 발사 후 이탈</option></select></label><button id=\"tactic-load\">상황 준비</button><button id=\"tactic-fire\">1회 공격 결과</button></div><p id=\"tactic-help\"></p></details></div>\n<div class=\"pane\" id=\"review-pane\" role=\"tabpanel\" hidden><div class=\"row\"><label>구간 <select id=\"phase\"><option value=\"0\">전개</option><option value=\"1\">변형</option><option value=\"2\">재공격</option></select></label><button id=\"view-scene\">구간 보기</button><label>예고 <select id=\"tell-scene\"></select></label><button id=\"tell-view\">예고 보기</button><label class=\"check\"><input id=\"hard\" type=\"checkbox\"> 체력 절반</label></div><div class=\"row\"><button id=\"tell-step\">6프레임 진행</button><button id=\"step-scene\">1초 진행</button><button id=\"fire-scene\">2초 사격</button><button id=\"cycle-hue\">색 변경</button><button id=\"bomb-scene\">폭탄</button><label class=\"check\"><input id=\"auto\" type=\"checkbox\"> 자동 사격</label></div><p>빈 고리와 모이는 빛은 준비입니다. 구슬이 실체화되면 위험합니다.</p><details id=\"flow-panel\" hidden><summary>화요일 자동 경로 비교</summary><div class=\"row\"><select id=\"flow-choice\" aria-label=\"비교 경로\"><option value=\"1\">세 색 활용</option><option value=\"0\">같은 경로 · 빨강 고정</option></select><button id=\"flow-play\">흐름 재생</button><button id=\"flow-result\">첫 10초 결과</button><button id=\"flow-takeover\">직접 이어하기</button></div><p id=\"flow-status\"></p></details></div>\n</section>";
const css="\nbody{height:100vh;display:flex;flex-direction:column;overflow:auto}.room-title{display:flex;align-items:center;justify-content:space-between;padding:12px 24px;background:#101522;border-bottom:1px solid #30364b}.room-title div{display:flex;gap:18px;align-items:center}.room-title span{font:10px Georgia;letter-spacing:2px;color:#aeb2c7}.room-title strong{font-size:16px;letter-spacing:.02em}.room-title a{font-size:12px;text-decoration:none}#reviewbar{flex:none;background:#141b2a;padding:0 24px 12px;border-bottom:1px solid #30364b;font-size:12px}#reviewbar nav{display:flex;gap:20px;border-bottom:1px solid #30364b;margin-bottom:10px}#reviewbar button{font:inherit;padding:7px 12px;margin:0;letter-spacing:0;border-radius:5px;background:#202b3e;border:1px solid #45536c}#reviewbar nav button{border:0;border-bottom:2px solid transparent;border-radius:0;padding:11px 4px;background:none;color:#aeb6c9}#reviewbar nav button[aria-selected=true]{color:#f4e8cc;border-bottom-color:#d6bd85}#reviewbar .primary{background:#dec598;color:#111827;border-color:#dec598;font-weight:600}#reviewbar select{font:inherit;background:#1c2739;color:#eee;padding:6px;border:1px solid #45536c;border-radius:4px}#reviewbar .context,#reviewbar .row{display:flex;align-items:center;gap:10px;flex-wrap:wrap}#reviewbar .context{margin:0 0 10px}#reviewbar .row+.row{margin-top:8px}#reviewbar p{color:#aebacf;margin:8px 0 0;line-height:1.6}#reviewbar label{display:flex;align-items:center;gap:6px}#reviewbar .check{color:#aebacf}#scene-status{color:#93a3bb;margin-left:auto;font-size:11px}#day-help{color:#b5c1d4;flex:1;min-width:230px;line-height:1.5}#reviewbar details{margin-top:10px;padding-top:8px;border-top:1px solid #30364b}#reviewbar summary{cursor:pointer;color:#c7b48e;margin-bottom:8px}[hidden]{display:none!important}#stage-area{flex:1;min-height:260px;display:grid;place-items:center;overflow:hidden}#shell{width:min(100%,calc(var(--stage-height,600px) * 4 / 3));height:auto;aspect-ratio:4/3;top:0;transform:none;margin:0}#keys-help{flex:none;text-align:center;font-size:11px;color:#8e9bb1;padding:7px 10px;background:#101522}#stage-area{position:relative}@media(max-width:700px){.room-title{padding:8px 12px}.room-title span{display:none}#reviewbar{padding:0 12px 10px}#scene-status{width:100%;margin:0}#day-help{display:none}#reviewbar nav{gap:14px}.room-title strong{font-size:14px}}";
const dev=`<style>${css}</style><script>
const scene=document.getElementById('scene'),safe=document.getElementById('safe'),hard=document.getElementById('hard'),phase=document.getElementById('phase'),weapon=document.getElementById('weapon'),auto=document.getElementById('auto');
const dayLabels=['월 · 남색 / 교차 직조','화 · 빨강 / 멈춘 꽃','수 · 파랑 / 반사 꿈결','목 · 초록 / 궤도 정원','금 · 노랑 / 분기 수정','토 · 주황 / 쌍날개','일 · 보라 / 잃어버린 태양'];
const weaponLabels=['빨강 · 근거리 확산','주황 · 범위 폭발','노랑 · 관통창','초록 · 발사원 추적','파랑 · 넓은 파동','남색 · 주변 방어','보라 · 왕복 궤적'];
const weaponHelp=['가까이서 여러 갈래를 걷어냅니다. Shift를 누르면 좁고 길어집니다.','느린 탄이 명중하거나 사거리 끝에서 터집니다.','정렬된 여러 탄열을 한 발로 뚫습니다.','옆으로 벗어난 같은 색 발사원을 우선 추적합니다.','넓은 전방을 쓸어 여러 탄열을 끊습니다.','다가오는 남색 탄을 팽창하는 원으로 걷어냅니다. 다른 색은 위험합니다.','발사한 자리로 돌아와 폭발합니다. 이동·색 변경 후에도 남습니다.'];
scene.innerHTML=ORDER.map(i=>'<option value="'+i+'">'+dayLabels[i]+'</option>').join('');
weapon.innerHTML=weaponLabels.map((name,i)=>'<option value="'+i+'">'+name+'</option>').join('');
function sceneStatus(){document.getElementById('scene-status').textContent=weapons[held()]+' | '+Math.floor(clock/60)+'초 | 생명 '+p.hp+' | 파괴 '+m.broken+' | 발사원 '+m.stopped+' | 후속 '+m.emitted;document.getElementById('weapon-help').textContent=weaponHelp[held()]}
function protection(){p.inv=safe.checked?1e8:0}
function selectScene(warmup){auto.checked=false;keysClear();reset();beginCard(+scene.value);mode='play';intro=0;recovered=ORDER.indexOf(stage);if(hard.checked)boss.hp=boss.max*.45;p.inv=1e8;for(let i=0;i<warmup;i++)update();protection();paused=warmup>0;pausePanel.className='';last=0;accumulator=0;render();sceneStatus()}
${fs.readFileSync('tuesday-replay.js','utf8')}
let flowPlaying=false;
const dayHelp=['마지막 남색 밤. 3번 관통으로 관문을 뚫고 1번 파동으로 접근탄을 막으세요.','붉은 꽃을 열고, 2번 추적과 3번 폭발로 후속 발사원을 끊으세요.','푸른 탄열을 1번 파도로 쓸고, 3번 복귀탄을 남긴 뒤 이동하세요.','초록 공전 발사원을 1번으로 추적하고, 2번 폭발·3번 파동을 활용하세요.','황금 탄열을 1번으로 관통하고, 2번 복귀 폭발로 가지를 지우세요.','주황 날개 사이로 이동하며 1번 폭발과 2번 파동을 활용하세요.','보라 껍질을 열어 태양을 되찾으세요. 마지막 월요일의 달까지 모으면 세계가 복원됩니다.'].map((t,i)=>t+' 배색: '+['남색 · 파랑 · 보라','빨강 · 노랑 · 주황','파랑 · 남색 · 보라','초록 · 노랑 · 파랑','노랑 · 주황 · 초록','주황 · 빨강 · 노랑','보라 · 남색 · 파랑'][i]+'. 무기와 같은 색의 탄을 파괴하세요.');
const tells=[[20,200,320,380],[20,164,250,302,384],[20,200,330],[20,200,310],[20,200,400],[20,170,325],[20,230,305,420]];
function dayUI(){document.getElementById('day-help').textContent=dayHelp[+scene.value];document.getElementById('flow-panel').hidden=scene.value!=='1';document.getElementById('tell-scene').innerHTML=tells[+scene.value].map((t,i)=>'<option value="'+t+'">'+['첫 소환','중반 준비','후반 준비','마지막 준비','재공격'][i]+'</option>').join('')}
scene.onchange=()=>{flowPlaying=false;dayUI();selectScene(0);paused=true;render()};
for(const button of document.querySelectorAll('[data-panel]'))button.onclick=()=>{flowPlaying=false;auto.checked=false;keysClear();paused=true;scene.disabled=button.dataset.panel==='lab-pane';scene.parentElement.hidden=scene.disabled;if(!scene.disabled&&mode==='practice'){selectScene(0);paused=true}pausePanel.className='';for(const pane of document.querySelectorAll('.pane'))pane.hidden=pane.id!==button.dataset.panel;for(const tab of document.querySelectorAll('[data-panel]'))tab.setAttribute('aria-selected',String(tab===button));sceneStatus();render()};
const originalUpdate=update;update=()=>{if(flowPlaying&&(stage!==1||mode!=='play')){flowPlaying=false;keysClear();document.getElementById('flow-status').textContent='시연 종료 · 새로 재생하거나 직접 계속 진행할 수 있습니다.';}if(flowPlaying&&mode==='play')tuesdayInput(document.getElementById('flow-choice').value==='1');else if(auto.checked&&(mode==='play'||mode==='practice'))keys.z=true;originalUpdate()};
function weaponLab(demo){auto.checked=false;keysClear();reset();let k=+weapon.value;beginCard(DAY.indexOf(k));intro=0;mode='practice';m.lab=true;hand=[k,(k+2)%7,(k+4)%7];p.x=192;p.y=350;boss.hp=boss.max=1e6;
 for(let y of [110,170,240])for(let j=-2;j<=2;j++)shoot(192+j*14,y,0,0,k,4.5,{delay:0,life:100000});
 for(let side of [-1,1])for(let j=0;j<4;j++)shoot(192+side*52,300+j*16,0,0,k,5,{delay:0,life:100000});
 shoot(302,135,0,0,k,10,{delay:0,life:100000,emitter:{wait:180,period:120,pulses:8,n:5,spread:.16,speed:1.5}});
 protection();paused=false;if(demo){keys.z=true;cast();keysClear();for(let i=0;i<[10,18,5,15,9,10,16][k];i++){updateShots();updateBullets()}paused=true;}pausePanel.className='';last=0;accumulator=0;render();sceneStatus();}
document.getElementById('play-scene').onclick=()=>{flowPlaying=false;selectScene(0)};
document.getElementById('view-scene').onclick=()=>{flowPlaying=false;selectScene([[110,260,410],[100,285,490],[110,260,400],[110,210,330],[90,310,455],[100,240,405],[130,215,490]][+scene.value][+phase.value])};
document.getElementById('toggle-play').onclick=()=>{paused=!paused;pausePanel.className='';sceneStatus()};
document.getElementById('step-scene').onclick=()=>{paused=false;protection();for(let i=0;i<60;i++)update();paused=true;pausePanel.className='';render();sceneStatus()};
document.getElementById('fire-scene').onclick=()=>{paused=false;protection();keys.z=true;for(let i=0;i<120;i++)update();keysClear();paused=true;pausePanel.className='';render();sceneStatus()};
document.getElementById('cycle-hue').onclick=()=>{pressed.c=true;cast();clearPress();render();sceneStatus()};
document.getElementById('bomb-scene').onclick=()=>{pressed.x=true;cast();clearPress();render();sceneStatus()};
document.getElementById('weapon-demo').onclick=()=>{flowPlaying=false;weaponLab(true)};
document.getElementById('weapon-play').onclick=()=>{flowPlaying=false;weaponLab(false)};
function tacticLab(){
 flowPlaying=false;
 auto.checked=false;keysClear();reset();let k=+document.getElementById('tactic').value,c=[1,1,4,3,2,3,2][k];beginCard(c);mode='practice';intro=0;m.lab=true;p.ci=hand.indexOf(k);p.x=k===2?312:k===3?60:192;p.y=k===0?340:k===5?250:350;boss.x=20;boss.y=25;
 if(k===0||k===1){bloom(k===0?364:244,false);for(let i=0;i<37;i++)updateBullets()}if(k===2)crystals(180,false);if(k===3)garden(0,false);if(k===4||k===6)echo(180,false);
 if(k===5)for(let i=0;i<24;i++){let a=i*TAU/24;shoot(p.x+Math.cos(a)*100,p.y+Math.sin(a)*100,a+PI,3.2,5,4,{delay:0})}
 m.phase='TACTIC / '+weapons[k];document.getElementById('tactic-help').textContent=['가까운 다섯 탄열을 한 번에 엽니다.','연결되지 않은 세 무리를 폭발 하나로 제거합니다.','아래 세 겹을 뚫고 위 발사원까지 제거합니다.','일반 탄보다 공전하는 발사원을 먼저 노립니다.','넓은 파동이 별개의 전면 탄열을 함께 끊습니다.','접근 타이밍에 맞춰 원형 파동을 펼칩니다.','공격 후 왼쪽으로 이동·색 변경해도 복귀 폭발이 발사원을 지웁니다.'][k];
 protection();paused=true;pausePanel.className='';last=0;accumulator=0;render();sceneStatus();
}
document.getElementById('tactic-load').onclick=tacticLab;
document.getElementById('tactic-fire').onclick=()=>{
 tacticLab();let k=held();keys.z=true;cast();keysClear();
 for(let i=0;i<[25,60,45,85,42,40,80][k];i++){if(k===6&&i===24){pressed.c=true;cast();clearPress()}if(k===6&&i>=24&&i<59)p.x-=3.7;updateShots();updateBullets()}
 render();sceneStatus();
};
function flowReview(fast){
 flowPlaying=false;scene.value='1';dayUI();safe.checked=false;hard.checked=false;selectScene(0);flowPlaying=true;
 document.getElementById('flow-status').textContent='무적·폭탄 없이 동일 경로 비교 / 직접 이어하기로 조작 전환';
 if(fast){for(let i=0;i<600;i++)update();paused=true;pausePanel.className='';render();sceneStatus()}
}
document.getElementById('flow-play').onclick=()=>flowReview(false);
document.getElementById('tell-view').onclick=()=>{flowPlaying=false;selectScene(+document.getElementById('tell-scene').value)};
document.getElementById('tell-step').onclick=()=>{paused=false;for(let i=0;i<6;i++)update();paused=true;pausePanel.className='';render();sceneStatus()};
document.getElementById('flow-result').onclick=()=>flowReview(true);
document.getElementById('flow-takeover').onclick=()=>{flowPlaying=false;keysClear();paused=false;pausePanel.className='';document.getElementById('flow-status').textContent='직접 조작 중 · Z / C 또는 1 2 3 / 방향키';};
auto.onchange=()=>{keys.z=auto.checked};safe.onchange=()=>{protection();sceneStatus()};
document.addEventListener('keydown',()=>setTimeout(sceneStatus,30));setInterval(()=>{if(mode!=='title')sceneStatus()},500);
document.getElementById('title-view').onclick=()=>{flowPlaying=false;auto.checked=false;reset();goTitle();render()};
scene.value='1';phase.value='0';dayUI();reset();goTitle();render();
const fitStage=()=>document.getElementById('stage-area').style.setProperty('--stage-height',document.getElementById('stage-area').clientHeight+'px');new ResizeObserver(fitStage).observe(document.getElementById('stage-area'));fitStage();
</script>`;
const gameSource=fs.readFileSync('game.js','utf8').replaceAll('rainbow13k2026:high','rainbow13k2026:qa:high');
const page=fs.readFileSync('index.html','utf8').replace('<div id="shell">',controls+'<main id="stage-area"><div id="shell">').replace('<script src="game.js"></script>',()=>'</main><footer id="keys-help">방향키 이동 · Z 공격 · 1 / 2 / 3 또는 C 색 변경 · X 폭탄 · Shift 정밀 이동 · Esc 정지</footer><script>'+gameSource+'</script>').replace('</html>',dev+'</html>');
fs.writeFileSync('qa.html',page);
